PBL-9369 Orders-Sync-Financial-Status-Error (#68)
* PBL-9369 Update ShopifyOrder and (GraphQl) Order to handle a null financial status; remove unneeded ShopifyFulfillment enum; add .editorconfig to format code consistently with this solution and ignore unnecessary warnings (Warning CS1658 : Unexpected character '$'. See also error CS1056); fix XML doc formatting issue; update the tests creds .csv file path (started failing after switch to .NET Standard)

* PBL-9369 Add ShopifyOrder.RawFinancialStatus feature cleanup TODO